apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: k6kmhv1t8-python-gitops
  description: This is GitOps manifest for k6kmhv1t8-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: k6kmhv1t8-python
    backstage.io/kubernetes-id: k6kmhv1t8-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:k6kmhv1t8-python
