apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k6kmhv1t8-python
  janus-idp.io/tekton: k6kmhv1t8-python
  backstage.io/kubernetes-id: k6kmhv1t8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k6kmhv1t8-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
